include(ExternalProject)

set(TRACY_INSTALL_DIR ${CMAKE_CURRENT_BINARY_DIR}/tracy/install)
ExternalProject_Add(
  tracy_project
  GIT_REPOSITORY git@github.com:wolfpld/tracy.git
  GIT_TAG v0.9.1
  GIT_SHALLOW ON
  INSTALL_DIR ${TRACY_INSTALL_DIR}
  LOG_CONFIGURE ON
  LOG_BUILD ON
  LOG_UPDATE ON
  LOG_INSTALL ON
  LOG_OUTPUT_ON_FAILURE ON
  CMAKE_ARGS
    -DTRACY_ENABLE=$<BOOL:${USE_TRACY}>
    -DTRACY_NO_VSYNC_CAPTURE=ON
    -DTRACY_NO_FRAME_IMAGE=ON
    $<$<BOOL:${CMAKE_CROSSCOMPILING}>:-DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN_FILE}>
  INSTALL_COMMAND ${CMAKE_COMMAND} --install <BINARY_DIR> --prefix
                  <INSTALL_DIR>
)

set(TRACY_INSTALL_DIR
    ${CMAKE_CURRENT_BINARY_DIR}/tracy/install
    PARENT_SCOPE
)
